### ISSUE TITLE
two- or three-letter codes for @xml:lang

### ISSUE THREAD

**Issue by kshawkin** [open-editions/open-editions.org#13]
The following mention using two-letter codes on @xml:lang:

a) https://open-editions.org/about/

b) https://tei-c.org/extra/teiinlibraries/4.0.0/bptl-driver.html#index.xml-body.1_div.3_div.3_div.2

But this page mentions using 3-letter codes:

c) https://open-editions.org/contributing/

So I'm unclear on which is preferred practice for Open Editions.

**Comment by JonathanReeve** [comment]
So I looked into this, and it looks like, [while both two- and three-letter language codes are acceptable in the XML format, two-letter codes are preferable](https://www.w3.org/International/articles/language-tags/), unless there's more meaning conveyed by a three-letter code. I've just added this to the docs.
