### ISSUE TITLE
Open Edition's "list of conventions"

### ISSUE THREAD

**Issue by kshawkin** [open-editions/open-editions.org#14]
At https://open-editions.org/about/ you mention that Open Edition maintains a list of conventions.  Does that refer to https://open-editions.org/docs/ ?  If so, you might add a hyperlink on that phrase for clarity.

**Comment by JonathanReeve** [comment]
Good idea. I've just added a link in 58c6d0a. When we were just making these texts, before the project had a name, we were just keeping track of tags we were using in the repo's CONTRIBUTING.md file. But now that there are guiding principles for each text repo here, it makes sense to migrate these out of CONTRIBUTING.md and into open-editions.org/docs, where appropriate.
